
services:
  db:
    image: postgres:15.3
    container_name: postgres_container
    restart: always
    environment:
      - POSTGRES_USER=workreport_user
      - POSTGRES_PASSWORD=userpass
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data  # ✅ Persistent storage
      - ./init-scripts:/docker-entrypoint-initdb.d # ✅ Runs init.sql on first startup
    networks:
      - mynetwork
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U workreport_user -d workreport"]
      interval: 10s
      retries: 5
      timeout: 5s

  app:
    build:
      context: .
      args:
        - JAR_FILE=build/libs/WorkReportPlus-0.0.1-SNAPSHOT.jar
    container_name: workreportplus_app
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres
      - SPRING_DATASOURCE_USERNAME=workreport_user
      - SPRING_DATASOURCE_PASSWORD=userpass
      - SPRING_FLYWAY_URL=jdbc:postgresql://db:5432/postgres
      - SPRING_FLYWAY_USER=workreport_user
      - SPRING_FLYWAY_PASSWORD=userpass
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge

volumes:
  db_data:
