spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.flyway.url=${SPRING_FLYWAY_URL}
spring.flyway.user=${SPRING_FLYWAY_USER}
spring.flyway.password=${SPRING_FLYWAY_PASSWORD}
spring.flyway.schemas=public


# ? OAuth2 Google Login (No Changes)
spring.security.oauth2.client.registration.google.client-id=597184029878-43gfshsrb9ak1d2hckbjmtgarc2drsj1.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=profile,email
